# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

group :test do
  gem 'webmock'
  gem 'rspec'
end

gem 'danger', git: 'git://github.com/mataku/danger', branch: 'keyword-arguments'
